### ISSUE TITLE
European Escort Wagon passenger view

### ISSUE THREAD

**Issue by Maverick2797** [Marnack/dlxtrains_modpack#4]
The unlucky sod who gets put out in the weather on the veranda is stuck staring at the wall the whole trip when they could be turned around watching the tracks recede behind them.

The obvious solution would be for the person to just turn around and stop staring at a wall😶, but I think it's just easier to turn the whole wagon around and possibly shuffle the seating positions to account for the change. Not sure how that might affect the texture positioning though.

**Comment by Marnack** [comment]
Thanks Maverick2797.  Yes, I've been aware of this problem since creating the wagon.  It's due to a limitation in MT.  I have been looking at some workarounds since then but I haven't settled on an approach yet.  Your suggestion is a good partial fix if I had done that initially.  However, I'm concerned that flipping the orientation of the mesh at this point would mean that all existing instances of the wagon would then be in the wrong orientation at the end of existing trains.  I do want to fix this though so I'll keep the issue open.  Hopefully one of the workarounds I'm experimenting with will be viable.  Thanks for calling this out!

**Comment by Marnack** [comment]
Added support for the advtrains_attachment_offset_patch in the 1.9.0 release.
