### ISSUE TITLE
Add fluid tanks wagons?

### ISSUE THREAD

**Issue by AFCMS** [Marnack/dlxtrains_modpack#7]
Would be nice to have fluid tanks matching the colours of the other wagons of the mod and have them showcasing their content like the other ones.

**Comment by Maverick2797** [comment]
If you put certain items into the container wagons (eg filled buckets, technic cans, biofuel etc) the cargo container model will be replaced with a framed tank. This works for both single and double container wagons.
See dlxtrains_industrial_wagons/wagons.lua#L139 for a list of items that will display as framed tanks.
As to displaying  the contents, I can't imagine many tank wagons have windows IRL...

**Comment by Marnack** [comment]
Thanks for your feedback, AFCMS. Tank wagons are on my list of wagons to consider in a future update. However, since this modpack is currently intended for recreating wagons and locomotives that exist in the real world and I'm not familiar with any real world wagons where liquids are a visible cargo, I'm not sure if such a wagon would be a good fit for this modpack. If you can provide a link to an image of a real world wagon with visible liquid cargo I would be quite interested in it and would consider adding such a wagon.

In the meantime, Moretrains (https://content.minetest.net/packages/gpcf/moretrains/) has some nice tanker wagons and, as Maverick2797 noted, this modpack has container wagons that will appear loaded with ISO tanks when the wagons are loaded with containers of liquid.

**Comment by AFCMS** [comment]
> If you put certain items into the container wagons (eg filled buckets, technic cans, biofuel etc) the cargo container model will be replaced with a framed tank.

Didn't try that! Nice to know its possible.

**Comment by Marnack** [comment]
Tank wagons added in release 1.15.0
