### ISSUE TITLE
Licensing query: Rationale for choice of licence?

### ISSUE THREAD

**Issue by Montandalar** [Marnack/dlxtrains_modpack#8]
Hi Marnack,

It's not exactly an issue, but I thought this was the most appropriate place to ask. Was your choice of the Affero GPL licence  because you wanted to match the licence of the Advtrains core mod, perhaps believed in the benefits of copyleft attached to it or did you choose it because you believed you had to?

I ask this because it's come to my attention that (as far as I understand it) when shipping a "combined work" under the AGPL, the whole work falls under the AGPL, even permissively-licensed (BSD, MIT, etc) works. This doesn't affect Advtrains or DlxTrains in tandem, but it might affect a modpack or game - but only as far as the dependency tree goes, and not unrelated mods.

https://www.gnu.org/licenses/gpl-faq.html#AGPLv3CorrespondingSource

**Comment by Marnack** [comment]
Hi Montandalar,

Thanks for the link.

My choice of AGPL was deliberate.  In particular, I wanted to ensure that people running servers that included modified version of my mods would have to provide or publish the modified source to those mods.

I am not a legal expert but with respect to the “combined work” aspect, my understanding is that the intention is to ensure that not only is the modified source of the AGPL licensed software made available but also that it can be run/used by others. So for example, if someone modifies AGPL licensed software as well as one of its dependent components/libraries such that the AGPL software now depends on those changes to fully function then the modified component/library source would need to be published.  In other words, people should not try to circumvent the intention of the AGPL such that the modified AGPL licensed software can’t be fully used (even though its modified source was published) because it now depends on a modified component/library whose source is not available.

Where I see a potential problematic area is when changes that are wholly unrelated and non affecting to the AGPL licensed software are made to the dependent component/library.  The AGPL license might have stronger requirements or less finesse about this situation than I might have.  In theory though, it should be possible to architect or isolate changes to the component/library such that unrelated changes do not also have to be published.  However, I’ll certainly grant that it may be non-trivial to make such changes in some cases.

Anyway, it’s been a while since I studied the licenses in detail and I could be remembering things incorrectly.  Is there a more specific scenario about which you have concerns or questions?

Also, if you have suggestions or requests to make it easier to use dlxtrains in modpacks or games without the need to modify it or to minimize its dependencies (thereby lessening the chances for a “combined work” issue) I would be interested in trying to accommodate them.  Some of the items already on my to-do list that are somewhat related to that include eliminating the current required dependencies on mods from Minetest Game, and supporting materials from other mods and games, ideally in some mod agnostic way.

**Comment by Marnack** [comment]
I'm assuming that the issue can be closed now since there's been no additional discussion in nearly 3 months.
